#pragma once


#define IDS_DRIVER_NAME 101
#define IDS_DRIVER_DESCRIPTION 102
#define IDS_EQUIPMENT_TYPE 103
#define IDS_DRIVER_EQUIPMENT_TYPE 120
#define IDS_DRIVER_VERSION 104
#define IDS_DRIVER_INTEGRATION_COMPONENT_VERSION 105
#define IDS_DRIVER_DOWNLOAD_URL 106
#define IDS_DRIVER_ENVIRONMENT_INFORMATION 107
#define IDS_DRIVER_LOG_NAME 108
#define IDS_LOG_IS_ENABLED 109
#define IDS_IS_EMULATOR 110
#define IDS_INTEGRATION_COMPONENT 111
#define IDS_MAIN_DRIVER_INSTALLED 112
#define IDS_AUTO_SETUP 113
#define IDS_LOCALIZATION_SUPPORTED 114
#define IDS_NAME_EN 115
#define IDS_NAME_RU 116
#define IDS_DESCR 117
#define IDS_HAS_RET_VAL 118
#define IDS_IS_READABLE 119
