#pragma once

#ifndef DEFINEDRIVER_H
#define DEFINEDRIVER_H

// Определение версии драйвера подключаемого оборудования
#define DRIVER_REQUIREMENTS_VERSION_4_4  404
#define DRIVER_REQUIREMENTS_VERSION_4_3  403
#define DRIVER_REQUIREMENTS_VERSION_4_1  401
#define DRIVER_REQUIREMENTS_VERSION_3_9  309
#define DRIVER_REQUIREMENTS_VERSION_3_7  307
#define DRIVER_REQUIREMENTS_VERSION_3_6  306
#define DRIVER_REQUIREMENTS_VERSION_3_5  305
#define DRIVER_REQUIREMENTS_VERSION_3_4  304
#define DRIVER_REQUIREMENTS_VERSION_3_3  303
#define DRIVER_REQUIREMENTS_VERSION_3_2  302
#define DRIVER_REQUIREMENTS_VERSION_3_1  301
#define DRIVER_REQUIREMENTS_VERSION_2_5  205
#define DRIVER_REQUIREMENTS_VERSION_2_4  204

// Выбор текущей версии драйвера (можно изменить в зависимости от требований)
#ifndef DRIVER_REQUIREMENTS_VERSION
#define DRIVER_REQUIREMENTS_VERSION DRIVER_REQUIREMENTS_VERSION_3_2
#endif

#endif // DEFINEDRIVER_H
