#pragma once

#ifndef DEFINEDRIVER_H
#define DEFINEDRIVER_H

// Определение версии драйвера подключаемого оборудования
#define DRIVER_REQUIREMENTS_VERSION_4_4  4004
#define DRIVER_REQUIREMENTS_VERSION_4_3  4003
#define DRIVER_REQUIREMENTS_VERSION_4_1  4001
#define DRIVER_REQUIREMENTS_VERSION_3_9  3009
#define DRIVER_REQUIREMENTS_VERSION_3_7  3007
#define DRIVER_REQUIREMENTS_VERSION_3_6  3006
#define DRIVER_REQUIREMENTS_VERSION_3_5  3005
#define DRIVER_REQUIREMENTS_VERSION_3_4  3004
#define DRIVER_REQUIREMENTS_VERSION_3_3  3003
#define DRIVER_REQUIREMENTS_VERSION_3_2  3002
#define DRIVER_REQUIREMENTS_VERSION_3_1  3001
#define DRIVER_REQUIREMENTS_VERSION_2_5  2005
#define DRIVER_REQUIREMENTS_VERSION_2_4  2004

// Выбор текущей версии драйвера (можно изменить в зависимости от требований)
#ifndef DRIVER_REQUIREMENTS_VERSION
#define DRIVER_REQUIREMENTS_VERSION DRIVER_REQUIREMENTS_VERSION_3_4
#endif

#endif // DEFINEDRIVER_H
