#include "pch.h"
#include "localization_consts.h"

/*const std::wstring_view IDS_LC_DRIVER_NAME = L"IDS_DRIVER_NAME";
const std::wstring_view IDS_LC_DRIVER_DESCRIPTION = L"IDS_DRIVER_DESCRIPTION";
const std::wstring_view IDS_LC_EQUIPMENT_TYPE = L"IDS_EQUIPMENT_TYPE";
const std::wstring_view IDS_LC_DRIVER_VERSION = L"IDS_DRIVER_VERSION";
const std::wstring_view IDS_LC_DRIVER_INTEGRATION_COMPONENT_VERSION = L"IDS_DRIVER_INTEGRATION_COMPONENT_VERSION";
const std::wstring_view IDS_LC_DRIVER_DOWNLOAD_URL = L"IDS_DRIVER_DOWNLOAD_URL";
const std::wstring_view IDS_LC_DRIVER_ENVIRONMENT_INFORMATION = L"IDS_DRIVER_ENVIRONMENT_INFORMATION";
const std::wstring_view IDS_LC_DRIVER_NAME_ADDIN = L"IDS_DRIVER_NAME_ADDIN";
const std::wstring_view IDS_LC_DRIVER_ERROR_CONNECT_TERMINAL = L"IDS_DRIVER_ERROR_CONNECT_TERMINAL";
const std::wstring_view IDS_LC_DRIVER_ERROR_CONNECT_TIMEOUT = L"IDS_DRIVER_ERROR_CONNECT_TIMEOUT";
const std::wstring_view IDS_LC_DRIVER_ERROR_CONNECT_REFUSED = L"IDS_DRIVER_ERROR_CONNECT_REFUSED";
const std::wstring_view IDS_LC_DRIVER_ERROR_CONNECT_SECURITY = L"IDS_DRIVER_ERROR_CONNECT_SECURITY";
const std::wstring_view IDS_DRIVER_ERROR_CONNECT_PROTOCOL = L"IDS_DRIVER_ERROR_CONNECT_PROTOCOL";
*/

/// Define localization constant IDs