#pragma once
#ifndef LOCALIZATION_CONSTS_H
#define LOCALIZATION_CONSTS_H

#include <string_view>

inline constexpr std::wstring_view IDS_LC_DRIVER_NAME{ L"IDS_DRIVER_NAME" };
inline constexpr std::wstring_view IDS_LC_DRIVER_DESCRIPTION{ L"IDS_DRIVER_DESCRIPTION" };
inline constexpr std::wstring_view IDS_LC_EQUIPMENT_TYPE{ L"IDS_EQUIPMENT_TYPE" };
inline constexpr std::wstring_view IDS_LC_DRIVER_VERSION{ L"IDS_DRIVER_VERSION" };
inline constexpr std::wstring_view IDS_LC_DRIVER_INTEGRATION_COMPONENT_VERSION{ L"IDS_DRIVER_INTEGRATION_COMPONENT_VERSION" };
inline constexpr std::wstring_view IDS_LC_DRIVER_DOWNLOAD_URL{ L"IDS_DRIVER_DOWNLOAD_URL" };
inline constexpr std::wstring_view IDS_LC_DRIVER_ENVIRONMENT_INFORMATION{ L"IDS_DRIVER_ENVIRONMENT_INFORMATION" };
inline constexpr std::wstring_view IDS_LC_DRIVER_NAME_ADDIN{ L"IDS_DRIVER_NAME_ADDIN" };
inline constexpr std::wstring_view IDS_LC_DRIVER_ERROR_CONNECT_TERMINAL{ L"IDS_DRIVER_ERROR_CONNECT_TERMINAL" };
inline constexpr std::wstring_view IDS_LC_DRIVER_ERROR_CONNECT_TIMEOUT{ L"IDS_DRIVER_ERROR_CONNECT_TIMEOUT" };
inline constexpr std::wstring_view IDS_LC_DRIVER_ERROR_CONNECT_REFUSED{ L"IDS_DRIVER_ERROR_CONNECT_REFUSED" };
inline constexpr std::wstring_view IDS_LC_DRIVER_ERROR_CONNECT_SECURITY{ L"IDS_DRIVER_ERROR_CONNECT_SECURITY" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_CONNECT_PROTOCOL{ L"IDS_DRIVER_ERROR_CONNECT_PROTOCOL" };

inline constexpr std::wstring_view IDS_DRIVER_ERROR_DEVICEID_IDENTEFIER{ L"IDS_DRIVER_ERROR_DEVICEID_IDENTEFIER" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_EQUIPMENTTYPE_IDENTEFIER{ L"IDS_DRIVER_ERROR_EQUIPMENTTYPE_IDENTEFIER" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_CONNECTION_PARAMETERS{ L"IDS_DRIVER_ERROR_CONNECTION_PARAMETERS" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_INVALID_ACTION_NAME{ L"IDS_DRIVER_ERROR_INVALID_ACTION_NAME" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_NOT_FOUND_ACTION_NAME{ L"IDS_DRIVER_ERROR_NOT_FOUND_ACTION_NAME" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_INVALID_LANGUAGE_CODE{ L"IDS_DRIVER_ERROR_INVALID_LANGUAGE_CODE" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_UNSUPPORTED_LANGUAGE_CODE{ L"IDS_DRIVER_ERROR_UNSUPPORTED_LANGUAGE_CODE" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_INVALID_LOCALIZATION_PATTERN{ L"IDS_DRIVER_ERROR_INVALID_LOCALIZATION_PATTERN" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_INVALID_OPERATION_PARAMETERS{ L"IDS_DRIVER_ERROR_INVALID_OPERATION_PARAMETERS" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_INVALID_RESULT_TERMINAL{ L"IDS_DRIVER_ERROR_INVALID_RESULT_TERMINAL" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_INVALID_OPERATION_TERMINAL{ L"IDS_DRIVER_ERROR_INVALID_OPERATION_TERMINAL" };
inline constexpr std::wstring_view IDS_DRIVER_ERROR_OPERATION_NOT_SUPPORTED{ L"IDS_DRIVER_ERROR_OPERATION_NOT_SUPPORTED" };

#endif //LOCALIZATION_CONSTS_H