#pragma once

enum class POSTerminalCommandType : int {
	Cmd_NoSet = -1,
	Cmd_Purchase = 0,
	Cmd_Refund,
	Cmd_Withdrawal,
	Cmd_WithdrawalPartly,
	Cmd_CheckConnection,
	Cmd_ReadCardDiscount,
	Cmd_GetTerminalInfo,
	Cmd_PingDevice,
	Cmd_GetBalance,
	Cmd_ServiceRefund,
	Cmd_ServicePbP,
	Cmd_ServiceRefPbP,
	Cmd_ServicePbPperiod,
	Cmd_ServiceRefPbPperiod,
	Cmd_ServicePartlyRefPbPperiod,
	Cmd_ServicePartlyRefPbP,
	Cmd_ServiceInstantPbI,
	Cmd_ServiceRefPbI,
	Cmd_ServicePartlyRefPbI,
	Cmd_ServicePbIAct,
	Cmd_ServiceRefPbIAct,
	Cmd_ServicePartlyRefPbIAct,
	Cmd_ServiceGeneric,
	Cmd_Cashback,
	Cmd_Audit,
	Cmd_Verify,
	Cmd_VerifyCopy,
	Cmd_PrintReceiptNum,
	Cmd_PrintBatchJournal,
	Cmd_ReadBonusCard,
	Cmd_GetPinBonusCard,
	Cmd_PinChangeBonusCard,
	Cmd_GetPhoneNumber,
	Cmd_Preauthorization,
	Cmd_SaleCompletion,
	Cmd_GetOTPpassword,
	Cmd_GetReceiptInfo,
	Cmd_ServiceMessage_deviceBusy,
	Cmd_ServiceMessage_interrupt,
	Cmd_ServiceMessage_interruptTransmitted,
	Cmd_ServiceMessage_getMerchantList,
	Cmd_ServiceMessage_getMaskList,
	Cmd_ServiceMessage_debug,
	Cmd_ServiceMessage_getLastResult,
	Cmd_ServiceMessage_getLastStatMsgCode,
	Cmd_ServiceMessage_getLastStatMsgDescription,
	Cmd_ServiceMessage_identify,
	Cmd_ServiceMessage_getDiscountName,
	Cmd_ServiceMessage_correctTransaction
};